name: PR Validation

on:
  pull_request:
    branches:
      - master
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 'Deps: show dependencies metadata'
        uses: lirantal/github-action-new-dependencies-advisor@06912df98836c8698a9e7525795612b439ff7612
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn
      - run: yarn lint
      - run: yarn lint:lockfile
      - run: yarn lint:firefox

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn
      - run: yarn test
