name: Build and Release
on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Gets release info
        id: semantic_release_info
        uses: jossef/action-semantic-release-info@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        if: ${{ steps.semantic_release_info.outputs.git_tag }}
        run: |
          yarn
          yarn build
        env:
          BUILD_VERSION: ${{ steps.semantic_release_info.outputs.version }}

      - name: Chrome Extension upload & publish.
        if: ${{ steps.semantic_release_info.outputs.git_tag }}
        uses: MobileFirstLLC/cws-publish@2.1.1
        with:
          refresh_token: ${{ secrets.CHROME_MARKETPLACE_REFRESH_TOKEN }}
          client_id: ${{ secrets.CHROME_MARKETPLACE_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_MARKETPLACE_CLIENT_SECRET }}
          zip_file: './dist/chrome_${{ steps.semantic_release_info.outputs.version }}.zip'
          extension_id: 'fahpefingaaldhifdbnlipfjniabkiho'
          action: 'publish'
      
      - name: Upload Release Artifacts
        if: ${{ steps.semantic_release_info.outputs.git_tag }}
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.semantic_release_info.outputs.git_tag }}
          name: ${{ steps.semantic_release_info.outputs.git_tag }}
          body: ${{ steps.semantic_release_info.outputs.notes }}
          target_commitish: ${{ steps.commit_and_push.outputs.latest_commit_hash }}
          files: |
            ./dist/chrome*.zip
            ./dist/firefox*.xpi
